name: DevSecOps CI/CD Pipeline for OWASP Juice Shop

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Deploy OWASP Juice Shop
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Juice Shop Docker image
        run: |
          docker pull bkimminich/juice-shop

      - name: Start Juice Shop Docker Container
        run: |
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop

  security:
    name: Security Testing
    runs-on: ubuntu-latest
    needs: build
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # CodeQL for SAST
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript-typescript'
          queries: security-extended
          config: |
            paths-ignore:
              - 'data/static/codefixes'
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      
        

        #Snyk for SCA
      - name: Checkout repository
        uses: actions/checkout@master

      #Set up node for Snyk
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://juice-shop:3000'  
          
      - name: Upload ZAP report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: /home/runner/work/DevSecOps-CI-CD-Pipeline/DevSecOps-CI-CD-Pipeline/*.html