name: DevSecOps CI/CD Pipeline for OWASP Juice Shop

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write 
  security-events: write

jobs:
  build:
    name: Build and Deploy Juice Shop
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Juice Shop Docker Image
        run: docker pull bkimminich/juice-shop

  security_testing:
    name: Security Testing
    runs-on: ubuntu-latest
    needs: build

    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v4

      # # Set up Node.js environment
      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      # # SAST: CodeQL Security Analysis
      # - name: Initialize CodeQL
      #   uses: github/codeql-action/init@v2
      #   with:
      #     languages: javascript
      #     queries: security-extended
      #     config: |
      #       paths-ignore:
      #         - 'data/static/codefixes'
      # - name: Autobuild
      #   uses: github/codeql-action/autobuild@v2
      # - name: Perform CodeQL Analysis
      #   uses: github/codeql-action/analyze@v2
      #   with:
      #     category: "/language:javascript"
      #     output: "codeql-results"
      # - name: Upload codeQL results as artifact
      #   uses: actions/upload-artifact@v4
      #   with: 
      #     name: codeql-scan-results
      #     path: codeql-results/*.sarif

      # # SCA: Snyk Vulnerability Scanning
      # - uses: actions/checkout@master
      # - name: Install Dependencies
      #   run: npm install
      # - name: Create sarif-files directory
      #   run: mkdir -p sarif-files
      # - name: Run Snyk to check for vulnerabilities
      #   uses: snyk/actions/node@master
      #   continue-on-error: true
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     args: --sarif-file-output=snyk.sarif
      # - name: Upload result to GitHub Code Scanning
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: snyk.sarif
      # - name: Upload snyk results as artifact
      #   uses: actions/upload-artifact@v4
      #   with: 
      #     name: snyk-scan-results
      #     path: snyk.sarif
          
      # DAST: OWASP ZAP Scan
      - name: Start Juice Shop Container
        run: |
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop
          # Wait for container to be healthy
          timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 5; done' || false

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -d -x zap-results.xml -I'
      - name: Upload zap results as artifact
        uses: actions/upload-artifact@v4
        with: 
          name: zap-scan-results
          path: zap-results.xml